### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ricardomatias** [silent-disco/node-disco#1]
* [x] Users should be able to add songs by pasting the URL in the chat field
* [x] Song is persisted on the db
* [x] Soundcloud integration
* [x] Create Users sidebar
